
import java.util.Timer;
import java.util.TimerTask;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Turma A
 */
public class dasda extends javax.swing.JFrame {

    /**
     * Creates new form dasda
     */
    private double desiredtemp = 22;
    private int desiredhum = 70;
    private double currenttemp=22;
    private int currenthum=70;
    boolean celcius = true;

    public dasda() {
        initComponents();
        currentTemp.setText(currenttemp+"");
        currentH.setText("80%");
        simulateCurrentTemp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        console = new javax.swing.JScrollPane();
        consoleText = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        currentTemperature = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        desiredTemperature = new javax.swing.JLabel();
        lessTemperature = new javax.swing.JButton();
        plusTemperature = new javax.swing.JButton();
        currentTemp = new javax.swing.JLabel();
        desiredTemp = new javax.swing.JLabel();
        convertTemp = new javax.swing.JButton();
        currentTgrau = new javax.swing.JLabel();
        currentDgrau = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        currentHumidity = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        currentH = new javax.swing.JLabel();
        desiredH = new javax.swing.JLabel();
        plusHumidity = new javax.swing.JButton();
        lessHumidity = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        console.setEnabled(false);

        consoleText.setColumns(20);
        consoleText.setRows(5);
        consoleText.setEnabled(false);
        console.setViewportView(consoleText);

        jLabel1.setText("Current Temp: ");

        jLabel2.setText("Desired Temp: ");

        lessTemperature.setText("-");
        lessTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessTemperatureActionPerformed(evt);
            }
        });

        plusTemperature.setText("+");
        plusTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusTemperatureActionPerformed(evt);
            }
        });

        currentTemp.setText("undefined");

        desiredTemp.setText("undefined");

        convertTemp.setText("Convert to Fahrenheit ");
        convertTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertTempActionPerformed(evt);
            }
        });

        currentTgrau.setText("ºC");

        currentDgrau.setText("ºC");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(desiredTemp)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(currentDgrau)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(desiredTemperature))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(currentTemp)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(currentTgrau)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(currentTemperature)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lessTemperature)
                        .addGap(18, 18, 18)
                        .addComponent(plusTemperature)
                        .addGap(18, 18, 18)
                        .addComponent(convertTemp)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(currentTemperature)
                    .addComponent(currentTemp)
                    .addComponent(currentTgrau))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(desiredTemperature)
                    .addComponent(desiredTemp)
                    .addComponent(currentDgrau))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plusTemperature)
                    .addComponent(lessTemperature)
                    .addComponent(convertTemp))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel3.setText("Current Humidity:");

        jLabel4.setText("Desired Humidity:");

        currentH.setText("undefined");

        desiredH.setText("undefined");

        plusHumidity.setText("+");
        plusHumidity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusHumidityActionPerformed(evt);
            }
        });

        lessHumidity.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentHumidity))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lessHumidity)
                                .addGap(18, 18, 18)
                                .addComponent(plusHumidity))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desiredH)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(currentHumidity)
                    .addComponent(currentH))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(desiredH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lessHumidity)
                    .addComponent(plusHumidity))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(console)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(console, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void simulateCurrentTemp(){
        Timer timer = new Timer();
        TimerTask timerTask = new TimerTask(){
            @Override
            public void run(){
                currenttemp=Math.random()*30;
                currentTemp.setText(currenttemp+"");
            }
        };
        timer.scheduleAtFixedRate(timerTask,0,1000);
    }
    private void lessTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessTemperatureActionPerformed
        currentTemp.setText(currenttemp+"");
        desiredTemp.setText((desiredtemp+0.5)+"º");
        desiredtemp-=0.5;
        consoleText.setText(consoleText.getText()+"Fora removido -0.5º da temperatura desejada\n");
    }//GEN-LAST:event_lessTemperatureActionPerformed

    private void plusTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusTemperatureActionPerformed
        currentTemp.setText(currenttemp+"");
        desiredTemp.setText((desiredtemp+0.5)+"º");
        desiredtemp+=0.5;
        consoleText.setText(consoleText.getText()+"Fora adicionado +0.5º a temperatura desejada\n");
    }//GEN-LAST:event_plusTemperatureActionPerformed

    private void convertTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertTempActionPerformed
        if(celcius == true){
            double auxtemp = (currenttemp * 1.8 + 32);
            currenttemp=auxtemp;
            currentTemp.setText(currenttemp+"");
            currentTgrau.setText("ºF");
            currentDgrau.setText("ºF");
            convertTemp.setText("Convert to Celcius ");
            consoleText.setText(consoleText.getText()+"Temperatura convertida para Fahrenheit\n");
            celcius = false;
        }
        else{
            double auxtemp = (currenttemp - 32) /1.8;
            currenttemp=auxtemp;
            currentTemp.setText(currenttemp+"");
            currentTgrau.setText("ºC");
            currentDgrau.setText("ºC");
            convertTemp.setText("Convert to Fahrenheit ");
            consoleText.setText(consoleText.getText()+"Temperatura convertida para Celcius\n");
            celcius = true;
        }
    }//GEN-LAST:event_convertTempActionPerformed

    private void plusHumidityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusHumidityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plusHumidityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dasda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dasda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dasda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dasda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dasda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane console;
    private javax.swing.JTextArea consoleText;
    private javax.swing.JButton convertTemp;
    private javax.swing.JLabel currentDgrau;
    private javax.swing.JLabel currentH;
    private javax.swing.JLabel currentHumidity;
    private javax.swing.JLabel currentTemp;
    private javax.swing.JLabel currentTemperature;
    private javax.swing.JLabel currentTgrau;
    private javax.swing.JLabel desiredH;
    private javax.swing.JLabel desiredTemp;
    private javax.swing.JLabel desiredTemperature;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton lessHumidity;
    private javax.swing.JButton lessTemperature;
    private javax.swing.JButton plusHumidity;
    private javax.swing.JButton plusTemperature;
    // End of variables declaration//GEN-END:variables
}
